name: CI build for docker action
on:
  push:
    branches: [main]
    paths: [hello-world-docker-action/**]
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Run container action
        id: hello-action
        uses: ./hello-world-docker-action
        with:
          who-to-greet: '@wulfland'

      - name: output time from the container
        run: echo 'the time was ${{ steps.hello-action.outputs.time }}'
