name: GitHub Actions Demo
on:
  push:
    branches: [main]
    paths-ignore: .github/workflows
  pull_request:
    branches: [main]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
  
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'The job was trigger by event ${{ github.event_name }}'
      - run: echo 'The branch name is ${{ github.ref }}'

      - uses: actions/checkout@v3

      - name: list files in the repo
        run: |
          echo 'The repo ${{ github.repository }} contains the following items'
          tree
